mybatis:
  mapper-locations: classpath:mapperxml/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oii?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
